# Generated by Django 5.2.5 on 2025-08-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('ram', 'RAM'), ('case', 'Case'), ('storage', 'Storage'), ('cooling', 'Cooling')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=10, unique=True)),
                ('motherboard_name', models.CharField(max_length=200)),
                ('motherboard_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('psu_name', models.CharField(max_length=200)),
                ('psu_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cpus', models.ManyToManyField(related_name='configs', to='builder.cpu')),
                ('gpus', models.ManyToManyField(related_name='configs', to='builder.gpu')),
            ],
        ),
    ]
