# Generated by Django 5.2.5 on 2025-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('ram', 'RAM'), ('case', 'Case'), ('storage', 'Storage'), ('cooling', 'Cooling')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TierComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('psu', 'PSU')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.RemoveField(
            model_name='config',
            name='cpus',
        ),
        migrations.RemoveField(
            model_name='config',
            name='gpus',
        ),
        migrations.RemoveField(
            model_name='config',
            name='motherboard_name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='motherboard_price',
        ),
        migrations.RemoveField(
            model_name='config',
            name='psu_name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='psu_price',
        ),
        migrations.AddField(
            model_name='config',
            name='components',
            field=models.ManyToManyField(related_name='configs', to='builder.tiercomponent'),
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
    ]
