# Generated by Django 5.2.5 on 2025-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_globalcomponent_tiercomponent_delete_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcomponent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiercomponent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
