# Generated by Django 5.2.5 on 2025-08-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_globalcomponent_active_tiercomponent_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('shortName', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('psu', 'PSU'), ('ram', 'RAM'), ('case', 'Case'), ('storage', 'Storage'), ('cooling', 'Cooling')], max_length=20)),
                ('image', models.URLField(blank=True, help_text='Optional. An image URL, primarily for PC cases.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Part Components',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tier Configurations',
            },
        ),
        migrations.CreateModel(
            name='TierPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_group', models.CharField(choices=[('components', 'Fixed Components'), ('cpuOptions', 'CPU Options'), ('gpuOptions', 'GPU Options')], max_length=20)),
                ('part_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.partcomponent')),
                ('tier_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.tierconfig')),
            ],
            options={
                'ordering': ['tier_config', 'part_group', 'part_component__name'],
                'unique_together': {('tier_config', 'part_component')},
            },
        ),
        migrations.RemoveField(
            model_name='config',
            name='components',
        ),
        migrations.DeleteModel(
            name='GlobalComponent',
        ),
        migrations.AddField(
            model_name='tierconfig',
            name='parts',
            field=models.ManyToManyField(related_name='tier_configs', through='builder.TierPart', to='builder.partcomponent'),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='TierComponent',
        ),
    ]
