# Generated by Django 5.2.5 on 2025-09-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('shortName', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('headset', 'Headset'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('mousepad', 'Mousepad'), ('monitor', 'Monitor')], max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Peripherals',
                'ordering': ['type', 'name'],
            },
        ),
    ]
