# Generated by Django 5.2.5 on 2025-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripherals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peripheral',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g., 10.00 for 10% off)', max_digits=5),
        ),
    ]
