# Generated by Django 5.2.5 on 2025-09-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripherals', '0002_peripheral_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='peripheral',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
